window.BLOG_POSTS = [
 {
  "num": 1,
  "title": "We Voted to End Foreign Wars — So Why Are We Paying for Another One?",
  "slug": "we-voted-to-end-foreign-wars-so-why-are-we-paying-for-another-one",
  "category": "Politics & Power",
  "subcategory": "America First vs. Both Parties",
  "image": "assets/blog/post1.jpg",
  "paragraphs": [
   "Let me tell you something. We did not vote for this.",
   "In 2024, Americans went to the polls and said the same thing in every state, in every rural county, at every kitchen table: no more foreign wars. We were done sending our sons and our money to fight in places most people couldn't find on a map. That's what we voted for.",
   "And then what happened? We went to war with Iran. Not because Iran attacked us. Because Washington decided — again — that another country's problems were worth American lives and American dollars.",
   "Here's what it's cost you, and I want you to sit with it. The Strait of Hormuz got choked off, and gas prices climbed while your paycheck didn't. Diesel went up, which means everything that moves on a truck — your groceries, your feed, your fuel — went up right along with it. The military burned through munitions we spent years and billions building, weapons we may need to defend our own country. And now there's talk of a reconstruction deal. I'm assuming that bill lands on the American taxpayer, because it always does.",
   "We bomb it. Then we rebuild it. With your money. And nobody in Washington asked you.",
   "You want to know the part that makes my blood boil? They'll tell you this was about keeping you safe. Same thing they said about every war that drained this country and buried our kids. Meanwhile the people who voted to send the bombs sleep just fine, and the people who pay for them — you — get told to be grateful.",
   "I spent my time in Congress fighting this exact thing. Foreign wars dressed up as necessity, sold to a public that already said no. I'll keep saying it now that I'm out, louder, because there's no leadership left to muzzle me.",
   "We are the freest country in the world, and we can't even keep our own government from spending us into another war we didn't ask for. That's not freedom. That's a racket.",
   "So here's what I want you to do. Don't take my word for any of it. Do your own research. Look at what this cost, look at who profited, and look at who's rebuilding what we just destroyed. Then ask yourself if a single person in Washington asked your permission. They didn't. They never do. And that's exactly why we can't stop paying attention."
  ],
  "date": "Jun 30, 2026",
  "dateSort": 1782774000000,
  "readTime": "3 min read",
  "snippet": "Let me tell you something. We did not vote for this.",
  "pullQuote": "Let me tell you something. We did not vote for this.",
  "catSlug": "politics-power"
 },
 {
  "num": 2,
  "title": "I Backed the Movement. Then It Went to War Without Us.",
  "slug": "i-backed-the-movement-then-it-went-to-war-without-us",
  "category": "Politics & Power",
  "subcategory": "America First vs. Both Parties",
  "image": "assets/blog/post2.jpg",
  "paragraphs": [
   "I helped build the America First movement. I fought for it, I took the arrows for it, and I meant every word. So let me be honest with you about what it's like to watch the people you stood with turn around and do the exact thing you all promised you never would.",
   "We went to war with Iran. And I said no — loudly, publicly, and to the people who used to call me an ally. Because we did not vote for this. In 2024, Americans said it as clearly as they've ever said anything: no more foreign wars. No more American money and American lives spent on other countries' fights. That was the promise. That was the whole point.",
   "Then the bombs fell anyway. And when I said what half the country was thinking — that this betrayed the exact voters who put these people in power — I went from ally to enemy overnight. I've been called a traitor by people who used to put me on their stage.",
   "So let me tell you how I define a traitor, because it isn't the person who keeps her word after everyone else breaks theirs. A traitor is someone who serves foreign countries and themselves before the American people. By that definition, I know exactly who the traitors are, and it isn't me.",
   "Here's what this taught me, and it's the most important political lesson I've got. America First was never supposed to be a team you join. It's a test you apply — to every politician, every party, every single time. Does this serve the American people, or does it serve somebody else? The minute you turn it into a loyalty club, it stops meaning anything, because the people at the top will happily wave the flag while they do the opposite of what it stands for.",
   "I'm not on a team anymore, and I'm not interested in one. I answer to the same people I always have — the families who work, pay, and get lied to, and who were promised no more wars and got another one.",
   "They can call me whatever they want. I've been called worse by better. What they can't do is make me pretend I didn't see what I saw.",
   "So apply the test yourself, to everyone, including the people you like. Do your own research on who actually kept their word and who folded the moment it counted. That's the only loyalty ever worth anything — loyalty to the truth, not the team."
  ],
  "date": "Jun 28, 2026",
  "dateSort": 1782601200000,
  "readTime": "3 min read",
  "snippet": "I helped build the America First movement. I fought for it, I took the arrows for it, and I meant every word. So let me be honest with you about…",
  "pullQuote": null,
  "catSlug": "politics-power"
 },
 {
  "num": 3,
  "title": "They Tell You What to Care About. I'll Tell You What Actually Matters.",
  "slug": "they-tell-you-what-to-care-about-i-ll-tell-you-what-actually-matters",
  "category": "Politics & Power",
  "subcategory": "America First vs. Both Parties",
  "image": "assets/blog/post3.jpg",
  "paragraphs": [
   "Every single day, the news tells you what you're supposed to care about. The country you're supposed to worry about. The issue that's supposed to keep you up at night.",
   "Well, I don't know about you, but I'm sick and tired of hearing about the Strait of Hormuz.",
   "The Strait of Hormuz. A place I've never been, a place I'll never go, and a place I should never have to pay for. But turn on any cable network and that's the story, hour after hour, expert after expert, all of them very concerned and none of them talking about the thing hitting your actual life.",
   "Here's what they're not covering. The price of beef at your grocery store. The family of four that can't afford health insurance. The rancher in Texas watching a parasite spread across his herd while Washington calls it somebody else's problem. What's happening in your town, on your road, at your kitchen table.",
   "Why? Because the news is obsessed with whatever Washington is obsessed with. And Washington is always — always — focused somewhere else. Some other country. Some other crisis. Anywhere but here.",
   "The issue I care about is the United States of America. The American people. And what is actually plaguing us. Not a shipping lane on the other side of the planet that I'll never see but somehow end up paying for.",
   "I learned something the longer I was in politics. The stories they push hardest are usually the ones that keep you from looking at the stories they'd rather you ignore. Follow what they want you distracted from, and you'll usually find what actually matters.",
   "So here's my rule, and I'd offer it to you. When the whole machine is screaming at you to care about one thing, ask yourself what you'd be noticing if they weren't. Ask what's happening right where you live that nobody with a microphone wants to talk about.",
   "Then go find out for yourself. Do your own research. Because the people telling you what to care about have never once had your interests at heart."
  ],
  "date": "Jun 26, 2026",
  "dateSort": 1782428400000,
  "readTime": "3 min read",
  "snippet": "Every single day, the news tells you what you're supposed to care about. The country you're supposed to worry about. The issue that's supposed to…",
  "pullQuote": "Well, I don't know about you, but I'm sick and tired of hearing about the Strait of Hormuz.",
  "catSlug": "politics-power"
 },
 {
  "num": 4,
  "title": "What Is America First, Really?",
  "slug": "what-is-america-first-really",
  "category": "Politics & Power",
  "subcategory": "America First vs. Both Parties",
  "image": "assets/blog/post4.jpg",
  "paragraphs": [
   "People throw the phrase around like they invented it, and half of them couldn't tell you what it means. So let me tell you what it means to me, plainly, so there's no confusion.",
   "America First means your family before Davos. Your town before a foreign capital. Your paycheck before a donor's portfolio. It's not complicated, and it was never supposed to be.",
   "It means we don't send your money overseas while your own people go without. It means we don't fight other countries' wars with American lives and American dollars because it's good for someone's business. It means the government you pay for works for you first — not the lobbyists, not the \"international community,\" not whoever wrote the biggest check.",
   "For most of my life I watched both parties operate on exactly the opposite principle. America Last, across the board. Endless foreign wars. Endless foreign aid. Endless money for everyone except the working families footing the bill. They dressed it up in noble language, but strip the language away and it always came down to the same thing: your interests came last.",
   "America First is the correction. It's not isolationism, no matter what they call it. I want America strong, respected, and prosperous. But strength starts at home. A country that can't take care of its own farmers, workers, retirees, and sick has no business lecturing the rest of the world about anything.",
   "And here's the part they hate: America First puts the burden of proof on Washington. Every dollar spent, every deal signed, every war started has to answer one question — does this serve the American people? If it doesn't, it doesn't happen. That simple test would gut half of what this town does, which is exactly why the people who profit from the current arrangement fight it so hard.",
   "I believe in this country. I believe in the people who built it and keep it running — the ones who go to work, raise their kids, pay their taxes, and ask for almost nothing except a government that's on their side.",
   "America First just means it's finally their turn. That's the whole idea. And it's worth fighting for."
  ],
  "date": "Jun 24, 2026",
  "dateSort": 1782255600000,
  "readTime": "3 min read",
  "snippet": "People throw the phrase around like they invented it, and half of them couldn't tell you what it means. So let me tell you what it means to me,…",
  "pullQuote": "America First just means it's finally their turn. That's the whole idea. And it's worth fighting for.",
  "catSlug": "politics-power"
 },
 {
  "num": 5,
  "title": "Three Countries in Two Days: A Little Behind-the-Scenes",
  "slug": "three-countries-in-two-days-a-little-behind-the-scenes",
  "category": "Life & Family",
  "subcategory": "Personal Story / Behind-the-scenes",
  "image": "assets/blog/post5.jpg",
  "paragraphs": [
   "People see the fighter. The clips, the hearings, the arguments. What they don't usually see is the ordinary stuff — the travel, the marriage, the tired airport mornings. So let me pull the curtain back a little, because the ordinary stuff is where you actually get to know a person.",
   "Not long ago, Brian and I did three countries in two days. We woke up in Costa Rica, drove to the airport, flew to Houston, spent the night, had a great steak dinner, and flew on to Puerto Vallarta the next morning. By the time we landed I'd lost track of what day it was. If you've ever done that kind of back-to-back travel, you know it's equal parts exciting and exhausting — a lot more glamorous in the photos than it is at 5 a.m. in a security line.",
   "I'll tell you a small moment that made me laugh. Going through customs, they asked if we were bringing in any fruits or vegetables. Nope. I told them I was coming to eat the fruits and vegetables grown down here — not carry in the garbage from somewhere else. Brian and I got a kick out of that. It's a little thing, but it's the kind of little thing that reminds you to pay attention to what you're actually putting in your body, wherever you are.",
   "Here's what these trips remind me of every time. I do what I do — the fighting, the speaking, the refusing to shut up — because I love this country and the people in it. But you cannot pour from an empty cup. You have to rest. You have to laugh with the person you love. You have to get out of the noise long enough to remember why you're in it.",
   "Brian and I are a team. We travel together, we make decisions together, and we take care of our health together. A lot of what keeps me steady when the world is loud isn't a strategy or a talking point. It's having someone beside me who knows the real me, not the one on television.",
   "So this is the part of Life with MTG that isn't a fight. It's just life — a little travel, a little laughter, a lot of gratitude. I'll keep bringing you the battles, because there are plenty of them. But every now and then I want to bring you this too, because I think you're tired of only ever seeing people at war.",
   "More soon. Thanks for coming along."
  ],
  "date": "Jun 22, 2026",
  "dateSort": 1782082800000,
  "readTime": "3 min read",
  "snippet": "People see the fighter. The clips, the hearings, the arguments. What they don't usually see is the ordinary stuff — the travel, the marriage, the…",
  "pullQuote": null,
  "catSlug": "life-family"
 },
 {
  "num": 6,
  "title": "Who Profits When Washington Says It's \"Safe and Effective\"?",
  "slug": "who-profits-when-washington-says-it-s-safe-and-effective",
  "category": "Politics & Power",
  "subcategory": "Follow the Money",
  "image": "assets/blog/post6.jpg",
  "paragraphs": [
   "I want to give you a little background, because once you understand how this actually works, you'll never hear the phrase \"safe and effective\" the same way again.",
   "When I served on the committee overseeing the government's COVID response, I learned something most Americans have no idea about. Government scientists — the same experts whose agencies tell you what's safe, all drawing taxpayer-funded paychecks — can hold patents on medications and technologies their own agencies then approve and promote. They collect royalties on those products. Taxpayer-funded research, taxpayer-funded salaries, and then personal royalties on top.",
   "Now I want to be careful here, because I'm not a scientist and I won't pretend to be one. What I'm telling you is documented — government scientists holding patents and collecting royalties is a real, verified practice. Whether that constitutes a conflict of interest in any specific approval decision is something reasonable people can debate. But I'll tell you what it looks like from where I sit: it looks like the people telling you what's safe have a financial interest in you believing them.",
   "Follow the money. It's the simplest rule in politics and it applies here like it applies everywhere else. When someone tells you to trust them, ask what they gain from your trust. When an agency says a product is safe, ask whether anyone at that agency profits from the product being on the market.",
   "I'm not telling you to reject medicine or ignore doctors. I'm telling you to ask questions — the same questions you'd ask about any politician, any lobbyist, any deal that seems too good to be true. Who benefits? Who pays? And who's making the rules?",
   "The pharmaceutical industry is among the largest donors to the politicians who oversee the agencies that approve their products. That's not a conspiracy theory. That's public record. And once you see that loop — industry funds politicians, politicians oversee agencies, agencies approve industry products, scientists collect royalties — you understand why \"safe and effective\" deserves a harder look than we've been giving it.",
   "Do your own research. Look at the royalty disclosures. Look at the lobbying numbers. Look at who sits on which boards after they leave government. Then decide for yourself how much blind trust that system has earned."
  ],
  "date": "Jun 20, 2026",
  "dateSort": 1781910000000,
  "readTime": "3 min read",
  "snippet": "I want to give you a little background, because once you understand how this actually works, you'll never hear the phrase \"safe and effective\" the…",
  "pullQuote": null,
  "catSlug": "politics-power"
 },
 {
  "num": 7,
  "title": "Your Grocery Bill Isn't an Accident — It's a Policy Choice",
  "slug": "your-grocery-bill-isn-t-an-accident-it-s-a-policy-choice",
  "category": "Money & the Economy",
  "subcategory": "Cost of Living & Inflation",
  "image": "assets/blog/post7.jpg",
  "paragraphs": [
   "Go stand in the checkout line at your grocery store and watch people's faces. Watch them do the math on a package of ground beef. Watch them put something back. That's happening in every town in America right now, and I want to be clear about something: it is not an accident.",
   "Prices don't rise on their own. Beef, gas, diesel, eggs — the cost of everything you buy is the downstream result of choices made in Washington. When the government spends money it doesn't have and prints more to cover it, your dollar buys less. When a war chokes off a shipping lane, fuel goes up. When fuel goes up, everything that travels on a truck goes up with it. That's your whole grocery store.",
   "We learned this in elementary school. Supply and demand. When supply gets squeezed or the dollar gets weaker, prices climb. There's nothing mysterious about it. The only mystery is why the people in charge act surprised every single time, as if inflation were weather instead of the direct consequence of their own decisions.",
   "Here's what makes me angry. The families getting hit hardest are the ones who did everything right. They work. They budget. They don't overspend. And they're still watching their grocery bill climb faster than their paycheck, because a government they didn't authorize keeps making choices that land on their kitchen table.",
   "And when you point it out, they tell you the economy is strong. Strong for who? Not for the mom putting the beef back. Not for the family stretching one income across a bill that keeps growing. \"Strong economy\" is what people say when they've never had to check the price before they put something in the cart.",
   "I don't have a magic fix, and I won't insult you by pretending I do. But I can tell you the first step, and it's the one they don't want you to take: stop accepting that this is just how things are. It isn't. It's the result of specific choices, made by specific people, who answer to you.",
   "So pay attention to those choices. Do your own research on where your money's really going and why it's worth less every year. Because the checkout line doesn't lie, even when Washington does."
  ],
  "date": "Jun 18, 2026",
  "dateSort": 1781737200000,
  "readTime": "3 min read",
  "snippet": "Go stand in the checkout line at your grocery store and watch people's faces. Watch them do the math on a package of ground beef. Watch them put…",
  "pullQuote": null,
  "catSlug": "money-economy"
 },
 {
  "num": 8,
  "title": "Every Dollar Washington Prints, You Pay For",
  "slug": "every-dollar-washington-prints-you-pay-for",
  "category": "Money & the Economy",
  "subcategory": "Cost of Living & Inflation",
  "image": "assets/blog/post8.jpg",
  "paragraphs": [
   "There's a tax you pay that you never voted for, that never shows up on a ballot, and that nobody in Washington will admit is a tax at all. It's called inflation, and here's how it actually works.",
   "When the government spends more than it takes in — which is always — it makes up the difference by printing. And every new dollar that gets created makes the dollars already in your pocket worth a little less. Nobody passed a law to raise your taxes. They just quietly shrank the value of everything you've already earned and everything you've already saved.",
   "That's the part people miss. Inflation isn't only about the price of groceries this week. It's about what happens to the money you set aside. You worked, you saved, you did the responsible thing — and while it sat there, the government's spending was quietly eating away at what it's worth. You didn't lose a single dollar on paper. You just lost what those dollars can buy.",
   "I want you to sit with that, because it's the most honest way to understand what's happening to working families. You're not imagining it. Your money really is worth less than it was, and it's not because you did anything wrong. It's because the people spending your future never had to ask your permission, and they never had to feel the cost.",
   "This is the tax nobody votes for. It falls hardest on the people who play by the rules — the savers, the retirees, the folks who trusted that a dollar saved would be a dollar kept. And it rewards exactly the behavior that caused it: more spending, more printing, more debt piled on your grandchildren.",
   "I'm not here to sell you fear. The numbers are bad enough on their own, and I don't need to dress them up. What I'm asking is that you understand the mechanism, because once you see it, you can't unsee it. A dollar is a promise. And Washington has been breaking that promise a little more every single year.",
   "So here's where I'd start. Do your own research on what a dollar bought ten years ago versus what it buys today. Then ask yourself the harder question — not just how to spend carefully, but how to hold on to what you've already built when the people in charge keep making it worth less."
  ],
  "date": "Jun 16, 2026",
  "dateSort": 1781564400000,
  "readTime": "3 min read",
  "snippet": "There's a tax you pay that you never voted for, that never shows up on a ballot, and that nobody in Washington will admit is a tax at all. It's…",
  "pullQuote": null,
  "catSlug": "money-economy"
 },
 {
  "num": 9,
  "title": "The 15-Year Warning: What Actually Holds Its Value",
  "slug": "the-15-year-warning-what-actually-holds-its-value",
  "category": "Money & the Economy",
  "subcategory": "Cost of Living & Inflation",
  "image": "assets/blog/post9.jpg",
  "paragraphs": [
   "Let me give you a number and I want you to read it twice. After the dot-com crash at the turn of the century, the Nasdaq — the tech-heavy market — took roughly fifteen years to climb back to where it had been. Fifteen years. A whole stretch of someone's working life, just to get back to even.",
   "Read that again, because we don't talk about it enough. We remember the crash. We forget the fifteen years.",
   "Now here's why I'm bringing it up. We've lived through this pattern more than once. The dot-com bust. Then 2008, when the housing market took everything down with it. Then 2020. Every time, the story is the same: Main Street pays the price while Washington prints its way out. And every time, ordinary families are told to just ride it out, as if fifteen years were nothing.",
   "Now look at where we are. Inflation eating into everyday budgets. A national debt so large it stopped meaning anything to the people running it up. And an AI boom driving valuations to heights that make some very smart people very nervous. I'm not predicting a crash. I don't have a crystal ball and I won't pretend to. But I've watched enough cycles to know that \"this time is different\" is the most expensive phrase in America.",
   "So the question I keep coming back to isn't \"when's the next downturn.\" Nobody knows that. The question is simpler and more useful: through every one of those crashes — dot-com, 2008, 2020 — what actually held its value?",
   "Because some things did. Through every panic, through every printing spree, certain things held on while paper promises got shaky. That's not a stock tip and I'm not giving you one. It's a historical pattern worth understanding for yourself.",
   "Here's what I'd ask you to do. Don't take my word for it, and for heaven's sake don't take a TV pundit's. Go look at the long history yourself. Pull up the last twenty-five years and ask what survived each storm and what didn't. Do your own research.",
   "Because the fifteen-year warning isn't about fear. It's about time — the one thing you can't get back if you're caught unprepared. The people who came through those cycles best weren't the ones who panicked. They were the ones who understood, ahead of time, what actually holds."
  ],
  "date": "Jun 14, 2026",
  "dateSort": 1781391600000,
  "readTime": "3 min read",
  "snippet": "Let me give you a number and I want you to read it twice. After the dot-com crash at the turn of the century, the Nasdaq — the tech-heavy market —…",
  "pullQuote": "Read that again, because we don't talk about it enough. We remember the crash. We forget the fifteen years.",
  "catSlug": "money-economy"
 },
 {
  "num": 10,
  "title": "$27,000 a Year for a Family of Four — and They Call That a Plan",
  "slug": "27-000-a-year-for-a-family-of-four-and-they-call-that-a-plan",
  "category": "Money & the Economy",
  "subcategory": "Healthcare Affordability",
  "image": "assets/blog/post10.jpg",
  "paragraphs": [
   "I want to run some numbers by you, and I want you to feel them the way American families feel them.",
   "Health insurance for a family of four now averages around $2,300 a month. That's roughly $27,000 a year. Twenty-seven thousand dollars — before anyone actually gets sick. Then add the deductible, which can run seven to ten thousand dollars on top of that. So a kid breaks an arm, someone needs surgery, there's a car accident, and now that family isn't out $27,000. They're out closer to $37,000. And that's before all the out-of-pocket costs insurance finds a way not to cover.",
   "Read those numbers again, because they're obscene. A middle-class family is supposed to pay their mortgage, feed their kids, keep the lights on, and hand over $37,000 a year for the privilege of maybe being covered. It's not possible. It's not close to possible. And that's exactly why more than one in ten working-age adults in this country — tens of millions of people, many with jobs and showing up every day — don't have health insurance at all. Not because they're irresponsible. Because they simply cannot afford it.",
   "This is unforgivable. And I want to be honest about who's responsible, because both parties will point at the other one.",
   "The party that passed the law that got us here has watched the price of coverage more than double since. But let me tell you what the other side did about it. Nothing. I was in those rooms. I watched my own party campaign on fixing health care every single election cycle and then do absolutely nothing once they had the majority — the House, the Senate, and the White House. I stood in a fight over exactly this while the government was shut down, asking one question: what is our plan? And the answer, from leadership, was silence.",
   "So don't let anyone tell you this is a partisan issue with a partisan villain. It's a Washington issue. Both sides had the power to fix it. Neither did. Because the current system pays the right people, and the people it bankrupts don't write big enough checks to matter.",
   "I don't have all the answers on health care. Nobody honest does. But I know a broken system when the numbers are this indefensible. Look at your own premiums. Do the math yourself. And ask why the people you elected keep calling this a plan."
  ],
  "date": "Jun 12, 2026",
  "dateSort": 1781218800000,
  "readTime": "3 min read",
  "snippet": "I want to run some numbers by you, and I want you to feel them the way American families feel them.",
  "pullQuote": "I want to run some numbers by you, and I want you to feel them the way American families feel them.",
  "catSlug": "money-economy"
 },
 {
  "num": 11,
  "title": "The Retirement Lie",
  "slug": "the-retirement-lie",
  "category": "Money & the Economy",
  "subcategory": "Retirement & Washington's Reach",
  "image": "assets/blog/post11.jpg",
  "paragraphs": [
   "There's a promise millions of Americans have built their whole future on, and I need to be straight with you about it: it's running out of road.",
   "Social Security's retirement trust fund is projected to run dry within the next decade. When it does, the law triggers an automatic cut to benefits — not a maybe, a scheduled reduction that lands on the people who can least afford it. Everybody in Washington knows this. The projections aren't secret. They just don't like to say it out loud, because saying it out loud means admitting the promise they keep making is one they can't fully keep.",
   "Here's the math they don't want on a campaign poster. The system was built when there were around five workers paying in for every retiree drawing out. Today it's fewer than three. You don't need an economics degree to see that a structure like that eventually buckles. And when it does, the shortfall doesn't land on Washington. It lands on you.",
   "I'm not telling you this to frighten you. I'm telling you because the most dangerous thing you can do is build your retirement entirely on a promise that the people who made it are quietly walking back. If your whole plan is \"the government will take care of it,\" you are trusting the same institution that ran up tens of trillions in debt to suddenly become responsible with your old age.",
   "So what do you actually do? You stop building only on paper promises. You save deliberately. You diversify. And you put at least some of what you've worked for into things you actually control — real, tangible assets that don't depend on a government IOU staying good. Not because the sky is falling, but because a wise person doesn't stake everything on a single promise from a single institution with a track record like this one.",
   "I spent years watching Washington make commitments it had no plan to fund. The retirement promise is the biggest one of all, and the bill is coming due on a generation that did everything they were told to do.",
   "Do your own research on the trust fund and the timeline — it's all public. Then ask yourself the honest question: if that promise gets cut, what do I actually own that's mine? Because the people who come through this best will be the ones who asked that question early."
  ],
  "date": "Jun 10, 2026",
  "dateSort": 1781046000000,
  "readTime": "3 min read",
  "snippet": "There's a promise millions of Americans have built their whole future on, and I need to be straight with you about it: it's running out of road.",
  "pullQuote": null,
  "catSlug": "money-economy"
 },
 {
  "num": 12,
  "title": "When Paper Loses Value, What Do You Actually Own?",
  "slug": "when-paper-loses-value-what-do-you-actually-own",
  "category": "Money & the Economy",
  "subcategory": "Owning Real Assets",
  "image": "assets/blog/post12.jpg",
  "paragraphs": [
   "I've told you the dollar is worth less every year. I've told you the retirement promise is running out of road. So let me ask the question those two facts lead to, the one I keep coming back to myself: when paper loses value, what do you actually own?",
   "Think about what most people's wealth really is. Numbers on a screen. A balance in an account. A statement that says you have something. But those are claims — promises that the number will still mean something when you need it. And we've just spent a lot of time talking about how good Washington's promises have been lately.",
   "I'm a person who likes to control what I can control. I've said before that when it comes to my health, I'd rather take care of myself as best I can than hand my fate entirely to a system I don't trust. I think about money the same way. There's a peace of mind that comes from owning something real — something you can hold, something that doesn't evaporate because a government printed too much or a bank made a bad bet.",
   "For most of human history, that's how people protected what they built. Not with paper promises, but with real assets that held their worth across generations, through wars and crashes and currencies that came and went. That instinct isn't old-fashioned. It's wisdom that got buried under a century of being told to trust the system.",
   "Now let me be careful and honest with you, because you deserve that. I'm not telling you the world is ending. I'm not telling you to panic or dump everything and run for the hills — that's exactly the kind of fear-peddling I can't stand, and there's plenty of it out there. What I'm telling you is calmer and more durable than that: it is simply wise not to hold everything you own in a form that somebody else controls and can quietly devalue.",
   "That's it. That's the whole idea. Real things, that are actually yours.",
   "So here's what I'd ask you to do, and it's the same thing I ask on everything. Do your own research. Learn the difference between owning a claim and owning an asset. Understand what has held its value through history and what hasn't. Then decide for yourself what belongs in your own hands.",
   "Because when paper loses value — and it always eventually does — the only thing that protects you is what you actually own."
  ],
  "date": "Jun 8, 2026",
  "dateSort": 1780873200000,
  "readTime": "3 min read",
  "snippet": "I've told you the dollar is worth less every year. I've told you the retirement promise is running out of road. So let me ask the question those…",
  "pullQuote": "That's it. That's the whole idea. Real things, that are actually yours.",
  "catSlug": "money-economy"
 },
 {
  "num": 13,
  "title": "The Gold Scam That Targets the People Who Trust the Most",
  "slug": "the-gold-scam-that-targets-the-people-who-trust-the-most",
  "category": "Money & the Economy",
  "subcategory": "Owning Real Assets",
  "image": "assets/blog/post13.jpg",
  "paragraphs": [
   "I built my name on following the money and calling out people who prey on the trusting. So I want to warn you about a scam that targets the exact people I care about most — retirees and conservatives trying to protect their savings by owning something real.",
   "The instinct is a good one. When you don't trust the dollar and you don't trust Washington, wanting to own real, physical gold makes complete sense. The problem isn't the instinct. It's that a slice of the precious-metals industry has learned to exploit it.",
   "Here's the play, and I want you to see it clearly, because it depends on you not seeing it.",
   "You call about gold. Instead of selling you plain, standard bullion at a fair price, a salesman steers you toward \"exclusive\" or \"collector\" coins — what the industry calls numismatics. They'll tell you these are special, rare, a better deal. Here's what they don't tell you. Those coins can carry enormous markups baked into the price, sometimes far above what the metal is actually worth. And when you go to sell, there's often no real market for them, so you can't get your money back out at anything close to what you paid.",
   "Then there's the spread — the gap between the price they sell to you at and the price they'll buy back from you at. In the worst cases that gap is enormous, and it's buried where you'll never see it until it's too late. You hand over your retirement savings, and a huge chunk of it disappears into someone else's margin before you've even started.",
   "This makes me furious, because the people getting hurt are the people who did the right thing. They saw the problem. They took action. And they got taken advantage of by an industry that wraps itself in patriotism and faith while picking their pockets.",
   "So here's what I want you to know. If someone is pushing you toward \"exclusive\" coins, \"rare\" coins, or anything that isn't plain, standard bullion — ask why. Ask what the markup is. Ask what they'll buy it back from you at tomorrow. And if they can't give you a straight answer, walk away.",
   "Do your own research. Understand the difference between bullion and numismatics. Look at what a fair spread actually looks like. Because the people who prey on trust are counting on you not asking those questions — and the best defense you have is knowing exactly what to ask."
  ],
  "date": "Jun 6, 2026",
  "dateSort": 1780700400000,
  "readTime": "3 min read",
  "snippet": "I built my name on following the money and calling out people who prey on the trusting. So I want to warn you about a scam that targets the exact…",
  "pullQuote": "Here's the play, and I want you to see it clearly, because it depends on you not seeing it.",
  "catSlug": "money-economy"
 },
 {
  "num": 14,
  "title": "Do Your Own Research: Why I Stopped Letting the FDA Decide for Me",
  "slug": "do-your-own-research-why-i-stopped-letting-the-fda-decide-for-me",
  "category": "Health & Freedom Over Your Body",
  "subcategory": "Medical Freedom",
  "image": "assets/blog/post14.jpg",
  "paragraphs": [
   "Do your own research. I say it constantly, and some people roll their eyes at it. Let me tell you why I mean it more than almost anything.",
   "For most of my life, like most Americans, I assumed that if a government agency said a treatment was safe, it was safe, and if they said one wasn't, I should stay away. That's how we're all raised to think. The experts know. Trust the system.",
   "Then I got a closer look at how the system actually works, and I stopped outsourcing my health to it.",
   "Here's what changed my mind. Our FDA blocks treatments that millions of people around the world use safely and effectively — treatments that could help Americans heal, age better, and suffer less. And when you ask why something perfectly available in other countries is off-limits here, the answer often isn't safety. It's money. If the FDA approved many of the treatments Americans are flying overseas to get, the ones who'd lose the most are the pharmaceutical companies. And big pharma, as I've told you, is among the biggest funders of the lawmakers who oversee all of it.",
   "So we live in supposedly the freest country in the world, and we're not free to make our own informed choices about our own bodies. That's not a small thing. That's a fundamental question of who owns you — you, or an agency captured by the industry it's supposed to regulate.",
   "Now hear me clearly, because I'm not a doctor and I won't play one. I'm not telling you to ignore medical advice or chase every miracle cure on the internet. There's real junk out there and real risk. What I'm telling you is that \"the FDA hasn't approved it\" is not the same sentence as \"it doesn't work\" — and once you understand why, you can't just take the label at face value anymore.",
   "Taking your health into your own hands doesn't mean being reckless. It means being informed. It means talking to people who've actually done a treatment. It means reading the research yourself instead of accepting a headline. It means understanding who profits from your choices before you make them.",
   "I made a big decision about my own health by doing exactly that. I'll tell you that story another time. But the principle underneath it is one I'd give to anyone, about anything. Do your own research. Nobody is coming to do it for you, and the people who claim to have already done it aren't always on your side."
  ],
  "date": "Jun 4, 2026",
  "dateSort": 1780527600000,
  "readTime": "3 min read",
  "snippet": "Do your own research. I say it constantly, and some people roll their eyes at it. Let me tell you why I mean it more than almost anything.",
  "pullQuote": "Then I got a closer look at how the system actually works, and I stopped outsourcing my health to it.",
  "catSlug": "health-freedom"
 },
 {
  "num": 15,
  "title": "I Left the Country for Care America Wouldn't Let Me Have",
  "slug": "i-left-the-country-for-care-america-wouldn-t-let-me-have",
  "category": "Health & Freedom Over Your Body",
  "subcategory": "Medical Tourism",
  "image": "assets/blog/post15.jpg",
  "paragraphs": [
   "I flew out of the country to take care of my own health, and I want to tell you why — not to brag about it, but because you deserve to know your options, and Washington would rather you didn't.",
   "It's called medical tourism, and tens of millions of Americans are quietly doing it. They're getting on planes to Mexico, Costa Rica, Turkey, Germany, and more — for dental work, joint replacements, fertility treatment, surgeries, and treatments our own system either can't afford them or won't allow. And here's the number that ought to make you angry: they're saving anywhere from 40 to 80 percent compared to what the same care costs at home.",
   "Let me give you one example that stopped me cold. Insulin — a medication people literally need to stay alive, including children with type 1 diabetes — can cost a few dollars a vial in some other countries. A few dollars. Meanwhile Americans have paid, and fought, and rationed, and gone without, for a medication that costs almost nothing to make. That's not a free market. That's a broken one, engineered to keep you paying.",
   "So I did what a growing number of Americans do. I traveled, and I got care I believe in, at a fraction of what it would have cost here — care our own FDA won't even approve, for reasons I've told you have more to do with protecting big pharma than protecting you.",
   "Now I'll be honest with you about the tradeoffs, because I always am. I don't carry health insurance. That's a personal choice and a real risk, and I'd tell anyone considering it to look hard at that risk before they follow my lead. I'm not reckless about it — I eat well, I exercise, I sleep, and I invest in preventative care that keeps me healthy. But I'm not going to pretend there's no gamble in how I do things. There is, and I own it.",
   "What I won't accept is a system that makes leaving the country the smart financial decision for basic health care. That's a disgrace, and the fact that we've all just gotten used to it is worse.",
   "If any of this is new to you, do your own research. Look up what medical tourism actually involves, what it costs, and what people's experiences have been. You might decide it's not for you. But you should at least know the option exists — because nobody in our health care system is going to volunteer it."
  ],
  "date": "Jun 2, 2026",
  "dateSort": 1780354800000,
  "readTime": "3 min read",
  "snippet": "I flew out of the country to take care of my own health, and I want to tell you why — not to brag about it, but because you deserve to know your…",
  "pullQuote": null,
  "catSlug": "health-freedom"
 },
 {
  "num": 16,
  "title": "52 and Not Slowing Down: How I Actually Take Care of Myself",
  "slug": "52-and-not-slowing-down-how-i-actually-take-care-of-myself",
  "category": "Health & Freedom Over Your Body",
  "subcategory": "Fitness & Anti-aging",
  "image": "assets/blog/post16.jpg",
  "paragraphs": [
   "I'm 52 years old, and I have no intention of slowing down. Not this year, not in ten years. I want to talk to you honestly about how I actually take care of myself, because there's a lot of noise out there and not much plain talk.",
   "Here's the truth: most of what works isn't complicated, and it isn't for sale. I eat well — real food, not a cabinet full of processed junk. I exercise, consistently, not just when I feel like it. I protect my sleep like it matters, because it does. That's the foundation, and no supplement, no gadget, no shortcut replaces it. Anyone who tells you otherwise is usually selling something.",
   "I take a more proactive view of my health than most people are taught to. Instead of waiting until something breaks and then handing myself over to the system to fix it, I try to invest in staying strong and well in the first place. I'd rather spend my energy on prevention than on treatment. That's a mindset more than a routine — deciding that your health is your responsibility and acting like it.",
   "And I'll be straight with you about aging, because too many people are dishonest about it in both directions. I don't believe in pretending I'm 30. But I also don't accept the idea that getting older means quietly giving up — losing your strength, your energy, your sharpness, and calling it \"natural.\" A lot of what we accept as inevitable decline is really just years of neglect catching up. You have more say in how you age than anyone told you.",
   "I'm competitive about it, honestly. I don't want to just get by. I want energy for my family, clarity for my work, and the strength to keep fighting for the things I believe in. That takes upkeep. It takes discipline on the ordinary days when nobody's watching and it would be easier to skip it.",
   "None of this is about vanity. It's about capacity — the ability to show up, fully, for the people and the causes that need you. You can't fight for anything if you've let yourself fall apart.",
   "So if you've been telling yourself it's too late, or that this is just how it goes after a certain age, I'd push back on that gently. It's not too late. Start with the basics, be consistent, and do your own research on what works for your body. You've got more road ahead than you think — if you take care of the vehicle."
  ],
  "date": "May 31, 2026",
  "dateSort": 1780182000000,
  "readTime": "3 min read",
  "snippet": "I'm 52 years old, and I have no intention of slowing down. Not this year, not in ten years. I want to talk to you honestly about how I actually…",
  "pullQuote": null,
  "catSlug": "health-freedom"
 },
 {
  "num": 17,
  "title": "What I Learned Getting Stem Cells at 52",
  "slug": "what-i-learned-getting-stem-cells-at-52",
  "category": "Health & Freedom Over Your Body",
  "subcategory": "Fitness & Anti-aging",
  "image": "assets/blog/post17.jpg",
  "paragraphs": [
   "I did something a lot of people had opinions about: I traveled to Mexico and got a stem cell treatment. Since I've been open about it, I've learned there are a whole lot of armchair experts out there. So let me just tell you my own experience, honestly, and you can make of it what you will.",
   "First, what these actually are, because there's a lot of confusion. The stem cells I received come from the umbilical cord and placenta of babies who were safely delivered. They do not come from aborted fetuses. I would never do that — I'm proudly pro-life, and my record backs that up. These are cells that too often just get thrown away, and they can do remarkable things for healing and regeneration.",
   "Why did I do it? Because I take my health seriously and I'm always looking at how to age well and stay strong. This is a regenerative treatment — it works at the cellular level, and it's the kind of thing I'd rather invest in than wait around and treat problems after they start. It's also a treatment you essentially cannot get in the United States, because our FDA doesn't approve it. So I went where I could.",
   "Now let me be careful and fair, because you deserve honesty and not a sales pitch. I'm not a doctor. I can't promise you a single result, and I'd be lying if I said there's no risk in anything like this — you should always do your homework on any clinic and any procedure. I did mine. The clinic I chose was clean, professional, and highly regarded, with its own lab on site.",
   "What I can tell you is how I felt afterward. Within a few weeks I noticed my energy was better. I was sleeping better. I had more mental clarity, and a real drop in the inflammation I'd been carrying. That's my honest, personal experience — not a guarantee for you.",
   "And here's something I want to say plainly, as a Christian. I don't think any treatment is going to make me live one day longer than God has numbered for me. I believe He's already set my days. But I do believe I can take good care of the body He gave me and improve the quality of the days I've been given. Those two things aren't in conflict.",
   "If you're curious, do your own research — real research, not comment-section noise. Talk to people who've actually done it. Then decide what's right for you. That's all I'd ever ask."
  ],
  "date": "May 29, 2026",
  "dateSort": 1780009200000,
  "readTime": "3 min read",
  "snippet": "I did something a lot of people had opinions about: I traveled to Mexico and got a stem cell treatment. Since I've been open about it, I've…",
  "pullQuote": null,
  "catSlug": "health-freedom"
 },
 {
  "num": 18,
  "title": "What the Hell Is a Screwworm — and Why You Should Care",
  "slug": "what-the-hell-is-a-screwworm-and-why-you-should-care",
  "category": "Food & the Land",
  "subcategory": "Food Security as National Security",
  "image": "assets/blog/post18.jpg",
  "paragraphs": [
   "What the hell is a screwworm?",
   "That was my exact reaction when I first started seeing regular people talking about it online — and hearing almost nothing about it in the news. So I went to Texas to find out for myself, because the issue I care about is what's actually happening to America, not whatever Washington wants us distracted by that week.",
   "Here's what I learned, and why it should matter to you even if you've never set foot on a ranch. The New World screwworm is a parasite — a fly whose larvae eat the living flesh of warm-blooded animals. Cattle, yes, but also deer, wildlife, pets, and even people. We eradicated it from this country back in 1966, with a clever sterile-fly program that took years of hard work. Now, in 2026, it's back — the first case in the continental United States in decades turned up in a Texas calf this June, and the quarantine zone has already spread across parts of some twenty-one Texas counties.",
   "Food security is national security. I can't say that plainly enough. This is a threat to the cattle industry that feeds this country, and when you knock down the beef supply, prices at your grocery store climb — on top of the inflation already hammering your wallet. The rancher's problem in Texas becomes your problem at the checkout line faster than you'd think.",
   "And how did it get here? The same way so many of our problems get here — a government that watched a known threat move north for months and chose to be reactive instead of preemptive. We should have had a plan. We should have been prepared. Instead we were caught flat-footed, and now we're borderline too late, because it's already here.",
   "I'll tell you something else I heard while I was down there, and I'll be honest that I couldn't fully substantiate it — ranchers talking about cartels controlling some of the tools needed to fight this thing across the border, holding them back. I can't confirm that, so I'm not going to state it as fact. But I'll tell you it fits a pattern: our own security, our own food supply, dependent on a border and a foreign government we can't trust.",
   "The ranchers I met aren't panicking. They're doing the hard, daily work of protecting their herds — the way real Americans always do when Washington fails them. But they need people paying attention, and they need infestations reported instead of hidden out of fear of the government.",
   "So pay attention. Do your own research on where your food actually comes from and how fragile that chain really is. Because food security is national security — and right now, ours is under threat while the news talks about everything else."
  ],
  "date": "May 27, 2026",
  "dateSort": 1779836400000,
  "readTime": "3 min read",
  "snippet": "What the hell is a screwworm?",
  "pullQuote": null,
  "catSlug": "food-land"
 },
 {
  "num": 19,
  "title": "Big Tech Is Buying Up Rural America",
  "slug": "big-tech-is-buying-up-rural-america",
  "category": "Food & the Land",
  "subcategory": "Food Security as National Security",
  "image": "assets/blog/post19.jpg",
  "paragraphs": [
   "Drive down the back roads where I live, and where a lot of you live, and you'll start to notice something. Enormous windowless buildings going up behind chain-link fences. Land getting bought quietly. Power and water getting redirected. They call them data centers, and Big Tech is putting them up all over rural America — often in the very places that can least afford to lose their land, their water, and their electricity.",
   "I want to talk about this because almost nobody is, and that silence usually tells you something.",
   "Here's what's happening. The AI boom needs somewhere to live, and \"somewhere\" turns out to be rural America. These data centers consume staggering amounts of electricity and water to run and cool the machines. And they're landing in small communities that get told it's progress, told it's jobs, told to be grateful — while the strain on the local power grid, the local water supply, and the local land falls on people who were never really asked.",
   "This is a story about concentration. A handful of the most powerful companies on earth, pooling more and more control over the infrastructure that runs modern life, and doing it in the parts of the country with the least power to say no. The people making these deals don't live on these roads. They'll never feel the consequences. But the family farm down the way will.",
   "I'm not against technology, and I'm not against progress. But I've learned to ask a simple question whenever something this big moves this fast and this quietly: who benefits, and who pays? When the answer is \"the biggest corporations in the world benefit, and rural families pay,\" that's not progress. That's extraction with a nicer name.",
   "And rural America has been on the losing end of that arrangement for a long time. We feed this country. We fuel it. We fill its military. And in return we're treated as the place you put the things nobody else wants — the things that use up the water and the land and the power, out of sight of the people who profit from them.",
   "I think these communities deserve a real say in what gets built on top of them. And the rest of the country ought to be paying attention, because concentration of this much power in this few hands never stays confined to one zip code.",
   "Do your own research on what's being built near you and who's really behind it. Drive those roads and look. Because the future is being poured in concrete out where nobody's watching — and it's worth watching."
  ],
  "date": "May 25, 2026",
  "dateSort": 1779663600000,
  "readTime": "3 min read",
  "snippet": "Drive down the back roads where I live, and where a lot of you live, and you'll start to notice something. Enormous windowless buildings going up…",
  "pullQuote": "I want to talk about this because almost nobody is, and that silence usually tells you something.",
  "catSlug": "food-land"
 },
 {
  "num": 20,
  "title": "Depending on Less: Learning to Provide for Yourself",
  "slug": "depending-on-less-learning-to-provide-for-yourself",
  "category": "Food & the Land",
  "subcategory": "Self-sufficiency / Homesteading",
  "image": "assets/blog/post20.jpg",
  "paragraphs": [
   "There's a kind of freedom you can't vote for and nobody can give you. It's the freedom that comes from being able to provide for yourself — from depending a little less on systems that have proven, over and over, that they'll fail you when it counts.",
   "I've come to believe self-sufficiency isn't a hobby or a fad. It's a mindset, and it might be one of the most important things a family can build right now.",
   "Think about how much of your life runs through systems you don't control. Your food comes from a supply chain that stretches across the country and across borders — and we've just seen how fragile that is. Your power comes from a grid somebody else manages. Your security depends on institutions that answer to donors before they answer to you. None of that is inherently evil. But the more of your life that depends on somebody else's competence and goodwill, the more exposed you are when they let you down.",
   "So you claw a little of it back. You learn to grow some of your own food. You learn to store what you grow. You keep something set aside for when — not if — the supply chain hiccups or the power goes out or the price of everything jumps again. You build the skills to fix things, feed people, and keep going without waiting on permission or delivery.",
   "I'm not talking about bunkers and doomsday. I'm talking about the plain, practical independence that every generation of Americans before the last couple took for granted. My grandparents' generation knew how to provide for themselves as a matter of course. Somewhere along the way we traded that knowledge for convenience, and convenience turned out to have a price: dependence.",
   "The beautiful thing is that self-sufficiency also just makes you stronger and calmer. There's a real peace in knowing that if things get hard, you and your family will be okay because you prepared, because you have skills and supplies and each other. That's not fear. That's the opposite of fear. Fear is what you feel when you're completely dependent on a system you don't trust. Confidence is what you feel when you've built something that doesn't need it.",
   "You don't have to do it all at once, and you don't have to do it all. Start with one thing — a garden, a pantry, a skill. Do your own research and pick where to begin. Because the more you can provide for yourself, the less anyone else can hold over you. And that's freedom you can actually hold in your hands."
  ],
  "date": "May 23, 2026",
  "dateSort": 1779490800000,
  "readTime": "3 min read",
  "snippet": "There's a kind of freedom you can't vote for and nobody can give you. It's the freedom that comes from being able to provide for yourself — from…",
  "pullQuote": null,
  "catSlug": "food-land"
 },
 {
  "num": 21,
  "title": "God Has Numbered My Days — and It Changes How I Live Them",
  "slug": "god-has-numbered-my-days-and-it-changes-how-i-live-them",
  "category": "Faith",
  "subcategory": null,
  "image": "assets/blog/post21.jpg",
  "paragraphs": [
   "I'm a Christian, and I believe that God has numbered my days.",
   "I've said that publicly, and I meant it in a specific way I want to explain, because it shapes how I live more than almost anything else I could tell you.",
   "I take care of my health. I've been open about the treatments I've sought and the choices I've made to stay strong and well. But I don't do any of it believing I'll add a single day to my life beyond what God has already set for me. I don't think that's how it works. I believe He has numbered my days, every one of them, and that isn't in my hands.",
   "So what's the point of taking care of yourself, if the number's already set? Here's how I hold it. I can't change how many days I'm given. But I can do something about the quality of those days. I can be strong instead of frail, clear instead of foggy, present instead of worn out — for the people I love and the work I'm called to do. Stewardship of the body God gave me, for the time He's given me. Those two beliefs don't fight each other. They fit together.",
   "There's a freedom in this that I wish more people had. When you truly believe your days are numbered by God, you stop living in fear of death — and once you're not afraid of that, there's very little left that can control you. It's a big part of why I can say what I say and take the hits I take. I'm not fearless because I'm tough. I'm settled because I know Who holds my days.",
   "It also changes how I spend those days. If they're numbered and I don't know the number, then none of them are throwaways. That makes you less patient with things that don't matter and more devoted to the things that do — your faith, your family, your purpose. It puts a kind of weight on ordinary time that's easy to miss when you assume you've got forever.",
   "I don't preach at people, and I'm not going to start now. Faith is personal, and yours is yours. But you asked to know me, and this is the center of me — not a talking point, the actual foundation I stand on when everything else is shaking.",
   "God has numbered my days. I intend to live every one of them well, use them for something that matters, and not waste a single one being afraid. I'd wish the same for you."
  ],
  "date": "May 21, 2026",
  "dateSort": 1779318000000,
  "readTime": "3 min read",
  "snippet": "I'm a Christian, and I believe that God has numbered my days.",
  "pullQuote": "I'm a Christian, and I believe that God has numbered my days.",
  "catSlug": "faith"
 }
];

window.BLOG_CATEGORIES = [
 {
  "slug": "politics-power",
  "name": "Politics & Power",
  "description": "Where the real fights are — who holds power, who pays for it, and who Washington actually answers to."
 },
 {
  "slug": "money-economy",
  "name": "Money & the Economy",
  "description": "Your paycheck, your savings, your grocery bill — and the Washington choices behind every number."
 },
 {
  "slug": "health-freedom",
  "name": "Health & Freedom Over Your Body",
  "description": "Medical freedom, honest talk about aging, and the right to make your own choices about your own body."
 },
 {
  "slug": "food-land",
  "name": "Food & the Land",
  "description": "Food security is national security — rural America, the family farm, and who's really buying up the land."
 },
 {
  "slug": "life-family",
  "name": "Life & Family",
  "description": "The part that isn't a fight — travel, marriage, and the ordinary life behind the headlines."
 },
 {
  "slug": "faith",
  "name": "Faith",
  "description": "The foundation underneath all of it — faith, purpose, and living like your days are numbered."
 }
];
